### ISSUE TITLE
Mac OS X compatability issues

### ISSUE THREAD

**Issue by ChrisCummins** [ChrisCummins/emu#13]
```
 ./scripts/run-tests.sh                                              19:30:49
    clean/deadlink PASS
    clean/in-progress PASS
    clean/lock PASS
    clean/orphans FAIL
    init/init PASS
    init/permissions PASS
    init/quiet PASS
    init/reinitialize PASS
    init/template PASS
    init/update PASS
    log/limit FAIL
    log/log PASS
    log/no-sink PASS
    log/push FAIL
    log/sinks FAIL
    log/summary FAIL
    push/dry-run PASS
    push/excludes FAIL
    push/max FAIL
    push/message FAIL
    push/no-sink FAIL
    push/push FAIL
    sink/add PASS
    sink/rm PASS
    sink/sink FAIL
    verify/hash FAIL
    verify/invalid-hash FAIL
    verify/sink-hash FAIL

14 passed, 14 failed
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1
head: illegal line count -- -1

A log file of failed tests can be found at 'test.log'
```

**Comment by ChrisCummins** [comment]
Version 0.2.1 appears to be stable and functional on OS X. Master is broken.

**Comment by ChrisCummins** [comment]
`emu push` using v0.2.1 fails after file transfer:

```
sent 3.17M bytes  received 414.76K bytes  3.75K bytes/sec
total size is 300.25G  speedup is 83707.75
origin: File transfer complete (1187.08s), creating snapshot.
Creating sha1sum checksum worker thread...
Creating disk usage worker thread...
Checksum worker thread complete in 332.3s.
Disk usage worker thread complete in 332.3s.
Traceback (most recent call last):
  File "/usr/local/bin/emu-push", line 4, in <module>
    __import__('pkg_resources').run_script('emu==0.2.1', 'emu-push')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/emu-0.2.1-py2.7.egg/EGG-INFO/scripts/emu-push", line 64, in <module>
    ret = main(argv, len(argv))
  File "/usr/local/lib/python2.7/site-packages/emu-0.2.1-py2.7.egg/EGG-INFO/scripts/emu-push", line 57, in main
    verbose=options.verbose)
  File "/usr/local/lib/python2.7/site-packages/emu-0.2.1-py2.7.egg/emu/__init__.py", line 313, in push
    verbose=verbose)
  File "/usr/local/lib/python2.7/site-packages/emu-0.2.1-py2.7.egg/emu/__init__.py", line 930, in create
    size = du_t.get()
  File "/usr/local/lib/python2.7/site-packages/emu-0.2.1-py2.7.egg/emu/__init__.py", line 2211, in get
    return stdout.split()[0]
IndexError: list index out of range
emu push -vfi  6.24s user 41.18s system 3% cpu 25:19.82 total
```

**Comment by ChrisCummins** [comment]
Fixed
